### ISSUE TITLE
hoi

### ISSUE THREAD

**Issue by whippingdot** [tsunami-or-something/tsunami-or-something#1]
just to say you have millions of issues 👍

**Comment by tsunami-or-something** [comment]
bruh are you stupid anybody with half a brain would realize that
- 1, your stalking my inactive profile
- 2, thats a very rude thing to say

![image](https://user-images.githubusercontent.com/73726677/115449974-9c2af180-a1d8-11eb-9328-54be039e0446.png)

**Comment by whippingdot** [comment]
> bruh are you stupid anybody with half a brain would realize that
> 
> * 1, your stalking my inactive profile
> * 2, thats a very rude thing to say
> 
> ![image](https://user-images.githubusercontent.com/73726677/115449974-9c2af180-a1d8-11eb-9328-54be039e0446.png)

lul i was just looking at who I was following yesterday... I was trying to unfollow random people. When i saw your profile I wanted to see what you were doing and so...

Also i just looked at your README and saw that you said that the stats thing was wrong cause you have more issues. That cracked me up so I created this issue.

**Comment by iop3** [comment]
> cracked me up

same
